CREATE TABLE `user_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `steam_id` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `assetid` VARCHAR(255) NOT NULL,
  `classid` VARCHAR(255) NOT NULL,
  `image` TEXT NOT NULL,
  `appid` VARCHAR(255) NOT NULL,
  `price` INT NOT NULL,
  `withdrawn` BOOLEAN NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (steam_id) REFERENCES users(steam_id)
);