CREATE TABLE `user_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `assetId` VARCHAR(255) NOT NULL,
  `withdrawn` BOOLEAN NOT NULL DEFAULT 0,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `transactionId` VARCHAR(255),
  PRIMARY KEY (`id`),
  UNIQUE (`assetId`),
  FOREIGN KEY (`userId`) REFERENCES `users`(`userId`)
);